version: "3.3"

services:
  database:
    container_name: portal-database
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5433:5432"

  backend:
    container_name: portal-backend
    build:
      dockerfile: Dockerfile
      context: ../backend
    restart: always
    environment:
      - JDBC_URL=jdbc:postgresql://portal-db:5432/${POSTGRES_DB}
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - TWITTER_API_KEY
      - TWITTER_SECRET_KEY
      - TWITTER_ACCESS_TOKEN
      - TWITTER_SECRET_TOKEN
    ports:
      - "127.0.0.1:8080:8080"

  nginx:
    container_name: portal-nginx
    build:
      dockerfile: Dockerfile
      context: ../dev-ops/nginx
    restart: always
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "443:443"
      - "80:80"

  frontend:
    container_name: portal-frontend
    build:
      dockerfile: Dockerfile
      context: ../frontend
    restart: always
    volumes:
      - /app
      - /app/node_modules

volumes:
  frontend-build:
    external: true
